apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-2
  namespace: webapp2
spec:
  dnsNames:
    - kubeblzapp.ml
  secretName: blzapiapp-lets-encrypt-prod-tls
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer