apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-2
  namespace: webapp2
spec:
  dnsNames:
    - kubeblzapp.ml
    - www.kubeblzapp.ml
  secretName: webapp2-tls
  issuerRef:
    name: prod-issuer
    kind: Issuer
