apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    #kubernetes.io/ingress.class: "ingress-nginx-controller-67759f896-2kqf4"
    kubernetes.io/ingress.global-static-ip-name: "kube3"
  name: webapp3
spec:
  tls:
  - hosts:
    - kube-3.ml
    secretName: webapp3-tls
  rules:
  - host: kube-3.ml
    http:
      paths:
      - path: /
        # pathType: Prefix
        backend: 
          serviceName: web-3-service
          servicePort: 80