apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.global-static-ip-name: "kube3"
  name: webapp3
spec:
  tls:
  - hosts:
    - kube3.ml
    secretName: webapp3-tls
  rules:
  - host: kube3.ml
    http:
      paths:
      - path: /
        # pathType: Prefix
        backend: 
          serviceName: webapp3-service
          servicePort: 80