apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: webapp2
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web2-static-ip"
    
spec:
  tls:
  - hosts:
    - kubeblzapp.ml
    - www.kubeblzapp.ml
    secretName: webapp2-tls

  rules:
  - host: kubeblzapp.ml
    http:
      paths:
      - backend:
          serviceName: web-2-service
          servicePort: 80

  - host: www.kubeblzapp.ml
    http:
      paths:
      - backend:
          serviceName: web-2-service
          servicePort: 80     
  